version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 20
    commands:
      - echo "=== 現場検証スタート ==="
      - pwd
      - ls -la
      - echo "=== 現場検証エンド ==="
      - cd vite-project
      - npm install

  pre_build:
    on-failure: ABORT
    commands:
      - node -v

  build:
    on-failure: ABORT
    commands:
      - cd vite-project
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: vite-project/dist
